name: build-ios

on:
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  PROJECT_PATH: commet

jobs:
  build-ios:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      - name: Code Generation
        run: |
          cd $PROJECT_PATH
          dart run scripts/codegen.dart

      - name: Build iOS (no codesign)
        run: |
          cd $PROJECT_PATH
          flutter build ios --no-codesign --release --dart-define BUILD_MODE=release --dart-define PLATFORM=ios
